output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_cert" {
  description = "Cluster cert"
  value       = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}

output "cluster_token" {
  description = "Cluster token"
  value       = data.aws_eks_cluster_auth.cluster.token
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "dns_base_domain" {
  description = "DNS base domain"
  value       = var.dns_base_domain
}

output "dns_base_domain_id" {
  description = "DNS base domain ID"
  value       = data.aws_route53_zone.base_domain.id
}

output "elb_zone_id" {
  description = "ELB zone id"
  value       = data.aws_elb_hosted_zone_id.elb_zone_id.id
}

output "kubeconfig_filename" {
  description = "Kubeconfig filename"
  value       = module.eks.kubeconfig_filename
}
output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "aws_acm_certificate" {
  description = "ACM cert ID"
  value       = aws_acm_certificate.eks_domain_cert.id
}
